import React, { useState } from "react";
import { View, Text, StyleSheet, ScrollView } from "react-native";
import { IconButton, List, Searchbar } from "react-native-paper";
import { CarCard } from "../components/CarCard";

export default function Overview() {
  const [searchValue, setSearchValue] = useState("");

  return (
    <View>
      <Searchbar
        placeholder="Search"
        onChangeText={(value) => setSearchValue(value)}
        value={searchValue}
      />
      <View style={{ padding: 15, gap: 10 }}>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
        <CarCard
          Acceleration={1234}
          Cylinders={23}
          Displacement={213}
          Horsepower={234}
          Miles_per_Gallon={123}
          Name="sdaf"
          Origin="dasf"
          Weight_in_lbs={123}
          Year="13213"
        ></CarCard>
      </View>
    </View>
  );
}
